### ISSUE TITLE
使用系统的默认输入法输入汉字会有问题

### ISSUE THREAD

**Issue by obama901** [BackNotGod/BNTextField-Limit#1]
如题,
这种情况下在输入时,会将输入的拼音字母也算作已输入的字符,导致比如我想输入三个汉字但是由于他们的拼音字母数量大于我所限制的字符数,而不能够一次性顺利的打上去.
搜狗输入法和科大讯飞输入法在汉字输入上则不会出现这样的问题可能是因为输入拼音的时候不会将拼音打印在textfield里面.
所以请看一下能不能解决这个问题,因为毕竟我们不能控制用户要使用的输入法.

**Comment by BackNotGod** [comment]
非常感谢你的issue🤠，新版本[1.1.1]修复了这个问题，详情请看[1.1.1](https://github.com/BackNotGod/BNTextField-Limit/commit/f3b69f71be4067b7a7848b902fc6286e6b257a6a)

**Comment by yusanlou** [comment]
> 如题,
> 这种情况下在输入时,会将输入的拼音字母也算作已输入的字符,导致比如我想输入三个汉字但是由于他们的拼音字母数量大于我所限制的字符数,而不能够一次性顺利的打上去.
> 搜狗输入法和科大讯飞输入法在汉字输入上则不会出现这样的问题可能是因为输入拼音的时候不会将拼音打印在textfield里面.
> 所以请看一下能不能解决这个问题,因为毕竟我们不能控制用户要使用的输入法.

非常感谢你的issue🤠，新版本[1.1.1]修复了这个问题，详情请看[1.1.1](https://github.com/BackNotGod/BNTextField-Limit/commit/f3b69f71be4067b7a7848b902fc6286e6b257a6a)

**Comment by obama901** [comment]
👌
